stages:
    - develop
deploy:
 only:
     - develop
     - merge request
 
 stage: develop
 
 script:
     - cd /var/www/mios/mios-backend/mios-crm-back-v2
     - git status
     - git checkout .
     - git pull
     - composer dump-autoload
     - php artisan cache:clear
 
 tags:
     - crm-back-develop
